#This file is not used anymore.
version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - docker build --build-arg NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL --build-arg=NEXT_PUBLIC_TENANT_NAME=$NEXT_PUBLIC_TENANT_NAME -t akosfi/storefront:$TENANT_ID -f ./docker/Dockerfile .

  post_build:
    commands:
      - docker push akosfi/storefront:$TENANT_ID
